<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="item">
        <?php if ($block->hasProductUrl()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else:?>
            <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()):?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
<!--            --><?php //if ($_options = $block->getOptionList()):?>
<!--                <dl class="item-options">-->
<!--                    --><?php //foreach ($_options as $_option) : ?>
<!--                        --><?php //$_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
<!--                        <dt>--><?php //$block->escapeHtml($_option['label']) ?><!--</dt>-->
<!--                        <dd>-->
<!--                            --><?php //if (isset($_formatedOptionValue['full_view'])): ?>
<!--                                --><?php ///* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
<!--                            --><?php //else: ?>
<!--                                --><?php //$block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
<!--                            --><?php //endif; ?>
<!--                        </dd>-->
<!--                    --><?php //endforeach; ?>
<!--                </dl>-->
<!--            --><?php //endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <label class="label" for="cart-<?= /* @escapeNotVerified */ $_item->getId() ?>-qty">
                <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
            </label>
            <div class="control qty">
<!--                <input id="cart---><?php ///* @escapeNotVerified */ $_item->getId() ?><!---qty"-->
<!--                       name="cart[--><?php ///* @escapeNotVerified */ $_item->getId() ?><!--][qty]"-->
<!--                       data-cart-item-id="--><?php //$block->escapeHtml($_item->getSku()) ?><!--"-->
<!--                       value="--><?php ///* @escapeNotVerified */ $block->getQty() ?><!--"-->
<!--                       type="number"-->
<!--                       size="4"-->
<!--                       title="--><?php //$block->escapeHtml(__('Qty')) ?><!--"-->
<!--                       class="input-text qty"-->
<!--                       data-validate="{required:true,'validate-greater-than-zero':true}"-->
<!--                       data-role="cart-item-qty"/>-->
                <form action="#" method="post" name="form">
                    <p><select name="list1" data-role="cart-item-qty" data-validate="{required:true,'validate-greater-than-zero':true}">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                        </select></p>
                </form>

            </div>
        </div>
    </td>

    <td class="subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
    <td class="remove">
        <div class="actions-toolbar">
            <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
        </div>
    </td>

</tr>
</tbody>
