<div class="delivery-container">
    <div class="title">
        <h2 class="title-vodafone"><?= /* @escapeNotVerified */ __('The benefits of Vodafone') ?></h2>
    </div>
    <div class="del delivery-free">
        <img src='<?php echo $this->getViewFileUrl('images/delivery/car1.png'); ?>' alt="image-icon">
        <p><span><?= /* @escapeNotVerified */ __('Free shipping from 25 $') ?></span></p>
    </div>
    <div class="del delivery-workdays">
        <img src='<?php echo $this->getViewFileUrl('images/delivery/clock.png'); ?>' alt="image-icon">
        <p><span><?= /* @escapeNotVerified */ __('Ordered on weekdays before 5 pm, delivered tomorrow') ?></span></p>
    </div>
    <div class="del delivery-back">
        <img src='<?php echo $this->getViewFileUrl('images/delivery/car2.png'); ?>' alt="image-icon">
        <p><span><?= /* @escapeNotVerified */ __('14 days to change your mind') ?></span></p>
    </div>
    <div class="del delivery-pay">
        <img src='<?php echo $this->getViewFileUrl('images/delivery/lock.png'); ?>' alt="image-icon">
        <p><span><?= /* @escapeNotVerified */ __('pay safely and quickly') ?></span></p>
    </div>
</div>